dist: bionic
language: shell
os: linux
jobs:
  include:
    - stage: "Tests"
      name: "Admin tests"
      language: node_js
      node_js: "12"
      cache:
        directories:
          - node_modules
      before_install:
        - cd admin
      install:
        - yarn install
      script:
        - yarn test && yarn build

    - name: "Backend tests"
      language: python
      python: "3.6"
      cache:
        pip: true
      services:
        - docker
        - mongodb
      before_install:
        - cd backend
      install:
        - pip install pytest==4.* pytest-cov coveralls
        - pip install -r requirements.txt
      script:
        - PYTHONPATH=`pwd` pytest --cov=src

    - name: "Frontend tests"
      language: python
      python: "3.6"
      cache:
        pip: true
      before_install:
        - cd frontend
      install:
        - pip install -r requirements.txt
        - pip install pytest==5.* py-w3c
      script:
        - BACKEND_URL=https://www.research-software.nl/api PYTHONPATH=. pytest --live


    - stage: "docker-compose integration tests"
      before_install:
        - cp rsd-secrets.env.example rsd-secrets.env
        - source rsd-secrets.env
        - docker-compose build
      script:
        - docker-compose --file docker-compose.yml --file docker-compose.test.yml run test

stages:
  - "Tests"
  - "docker-compose integration tests"
