version: '3'

services:

  admin:
    build:
      context: ./admin
    command: sh -c "rm -rf /build/* && cp -r /usr/share/nginx/html/* /build"
    container_name: rsd-admin
    volumes:
      - rsd_static_admin:/build

  auth:
    build:
      context: ./auth-github
    container_name: rsd-authentication
    env_file:
      - .env

  backend:
    build:
      context: ./backend
    container_name: rsd-backend
    depends_on:
      - database
    env_file:
      - .env

  backup:
    build:
      context: ./backup
    container_name: rsd-backup
    depends_on:
      - database
    env_file:
      - .env

  database:
    build:
      context: ./database
    command: --bind_ip 0.0.0.0
    container_name: rsd-database
    entrypoint: /mongo.sh
    volumes:
      - ./docker-volumes/db:/data/db

  frontend:
    build:
      context: ./frontend
    container_name: rsd-frontend
    depends_on:
      - backend
    env_file:
      - .env
    volumes:
      - rsd_static_frontend:/shared_static
      - ./docker-volumes/oaipmh-cache:/static/oaipmh-cache

  graphs:
    build:
      context: ./graphs
    container_name: rsd-graphs
    command: sh -c "rm -rf /build/* && cp -r /usr/share/nginx/html/graphs/* /build"
    env_file:
      - .env
    volumes:
      - rsd_static_graphs:/build

  harvesting:
    build:
      context: ./harvesting
    container_name: rsd-harvesting
    env_file:
      - .env
    depends_on:
      - backend
      - database
    volumes:
      - ./docker-volumes/oaipmh-cache:/oaipmh-cache

  nginx_ssl:
    container_name: rsd-nginx-ssl
    env_file:
      - .env
    image: rsdnlesc/docker-term-letsencrypt
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped
    volumes:
      - ./docker-volumes/cert:/cert
      - ./docker-volumes/letsencrypt:/etc/letsencrypt
    depends_on:
      - reverse-proxy

  reverse-proxy:
    build:
      context: ./reverse-proxy
    container_name: rsd-reverse-proxy
    depends_on:
      - frontend
      - backend
      - admin
      - auth
      - graphs
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - rsd_static_admin:/static_admin:ro
      - rsd_static_frontend:/static_frontend:ro
      - rsd_static_graphs:/static_graphs:ro

volumes:
  rsd_static_admin:
  rsd_static_frontend:
  rsd_static_graphs: