version: '3'

services:

  admin:
    build:
      context: ./admin
    command: sh -c "rm -rf /build/* && cp -r /usr/share/nginx/html/* /build"
    container_name: rsd-admin
    volumes:
      - rsd_static_admin:/build

  auth:
    build:
      context: ./auth-github
    container_name: rsd-authentication
    environment:
      # user should not have to change the values of the following environment variables:
      - AUTH_CALLBACK_URL=/admin
      - AUTH_ROOT=/auth
      # user needs to assign values to the following environment variables:
      - AUTH_GITHUB_CLIENT_ID
      - AUTH_GITHUB_CLIENT_SECRET
      - AUTH_GITHUB_ORGANIZATION
      - JWT_SECRET

  backend:
    build:
      context: ./backend
    container_name: rsd-backend
    depends_on:
      - database
    environment:
      # user should not have to change the values of the following environment variables:
      - BACKEND_ROOT=/api
      - DATABASE_HOST=database
      - DATABASE_NAME=rsd
      - DATABASE_PORT=27017
      - SCHEMAS_PATH=schemas
      # user needs to assign values to the following environment variables:
      - DOMAIN
      - JWT_SECRET
      
  backup:
    build:
      context: ./backup
    container_name: rsd-backup
    depends_on:
      - database
    environment:
      # user should not have to change the values of the following environment variables:
      - DATABASE_HOST=database
      - DATABASE_NAME=rsd
      - DATABASE_PORT=27017
      # user needs to assign values to the following environment variables:
      - BACKUP_CMD

  database:
    build:
      context: ./database
    command: --bind_ip 0.0.0.0
    container_name: rsd-database
    entrypoint: /mongo.sh
    volumes:
      - ./docker-volumes/db:/data/db

  frontend:
    build:
      context: ./frontend
    container_name: rsd-frontend
    depends_on:
      - backend
    environment:
      # user should not have to change the values of the following environment variables:
      - BACKEND_URL=http://backend:5001/api
    volumes:
      - rsd_static_frontend:/shared_static
      - ./docker-volumes/oaipmh-cache:/static/oaipmh-cache

  graphs:
    build:
      context: ./graphs
    container_name: rsd-graphs
    command: sh -c "rm -rf /build/* && cp -r /usr/share/nginx/html/graphs/* /build"
    volumes:
      - rsd_static_graphs:/build

  harvesting:
    build:
      context: ./harvesting
    container_name: rsd-harvesting
    depends_on:
      - backend
      - database
    environment:
      # user should not have to change the values of the following environment variables:
      - BACKEND_URL=http://backend:5001/api
      - DATABASE_HOST=database
      - DATABASE_NAME=rsd
      - DATABASE_PORT=27017
      # user needs to assign values to the following environment variables:
      - GITHUB_ACCESS_TOKEN
      - JWT_SECRET
      - ZOTERO_API_KEY
      - ZOTERO_LIBRARY
    volumes:
      - ./docker-volumes/oaipmh-cache:/oaipmh-cache

  nginx_ssl:
    container_name: rsd-nginx-ssl
    environment:
      # user should not have to change the values of the following environment variables:
      - SSL_FORWARD=http://reverse-proxy:80
      # user needs to assign values to the following environment variables:
      - SSL_ADMIN_EMAIL
      - SSL_DOMAINS
    image: rsdnlesc/docker-term-letsencrypt
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped
    volumes:
      - ./docker-volumes/cert:/cert
      - ./docker-volumes/letsencrypt:/etc/letsencrypt
    depends_on:
      - reverse-proxy

  reverse-proxy:
    build:
      context: ./reverse-proxy
    container_name: rsd-reverse-proxy
    depends_on:
      - frontend
      - backend
      - admin
      - auth
      - graphs
    restart: unless-stopped
    volumes:
      - rsd_static_admin:/static_admin:ro
      - rsd_static_frontend:/static_frontend:ro
      - rsd_static_graphs:/static_graphs:ro

volumes:
  rsd_static_admin:
  rsd_static_frontend:
  rsd_static_graphs:
